language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run coverage run --source './' --omit './test/*' -m pytest
  - pipenv run coverage report
  - pipenv lock -r > requirements.txt
