language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run coverage run --source './' --omit './test/*' -m pytest
  - pipenv run coverage report

deploy:
  provider: azure_web_apps
  username: aswe_deployment_user
  password:
    secure: "rj+y92iECvhrCOymBOc+8h9WXfwBGFOAaswhMCiWcb0rPVJ41OKNXE+UQdsCiJKi6Hwqgk/nBgbPeS8dZN6P28sLls8lKtTPq/7WZdKL23vnXRrZhmS0fSTcvWm95x9eQQZHLYrveCxo0M70zngi/Naova/yorEXBePpYe2mnUC5u/E/eK9glx+PaYnX11B+/aKH+IS4CHW4A1F9DfvPbmKjEHWsyrs2YVN/CnUaReX3L++mt6kHdA4L+2pcr0S44hYFi+IidSuxxoQC1VV5llbe/Qs+tCr4wLY5wQoQ9SdvGWa1zb7qXPuNoWk5sKyMOTkxFAJPl+rJWHWsatuUhhSvebJAT4tO0If01aYfSOMDCtLeI/22jLg0r/exrELN/lqRpJcJicYCEdOBeecYWAz/BsZ5Bxi2U8I2fUAxkh2IQAWA78xodDygWaMLMcFIQDy54LKWSEWM7rT4ZqK8z9KbDgr/uVsffT8pPUR4HaxQGe3fFlT1Ys1r/ozAhOufbdYuIs56D9WDaIDcsler0BX5n0WLVzJt2QJgLsFPdQKvg0EjXTSEXA8x4q+fLImKTNv2I5ffK8LNtlwf1uBMIK0G6sOr5KLFPrB1oR9mEJd5bylxaAuNsBGqKhW8QVQINH8X7yRRLsI8YVlfTD/ZKUXGX0c6vWpFkwbW2M1G9FA="
  site: cal-mon
